//
//  GrammarError.swift
//  C7 Project
//
//  Created by Savio Enoson on 11/11/25.
//

import Foundation
import SwiftUI


struct GrammarError: CustomStringConvertible, Codable, Hashable, Identifiable {
    var id: String { "\(originalStartChar)-\(originalEndChar)-\(type)" }
    
    let type: String
    let fullErrantType: String
    
    let originalText: String
    let originalStartChar: Int
    let originalEndChar: Int
    
    let correctedText: String
    let correctedStartChar: Int
    let correctedEndChar: Int
    
    var correctionRationale: String = "Standard English requires this correction to match accepted grammatical usage patterns."
    
    enum CodingKeys: String, CodingKey {
        case type, fullErrantType, originalText, correctedText
        case originalStartChar, originalEndChar, correctedStartChar, correctedEndChar
        case correctionRationale
    }
    
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        type = try container.decode(String.self, forKey: .type)
        fullErrantType = try container.decode(String.self, forKey: .fullErrantType)
        originalText = try container.decode(String.self, forKey: .originalText)
        originalStartChar = try container.decode(Int.self, forKey: .originalStartChar)
        originalEndChar = try container.decode(Int.self, forKey: .originalEndChar)
        
        correctedText = try container.decode(String.self, forKey: .correctedText)
        correctedStartChar = try container.decode(Int.self, forKey: .correctedStartChar)
        correctedEndChar = try container.decode(Int.self, forKey: .correctedEndChar)
        
        // Rationale will be generated by model
        correctionRationale = try container.decodeIfPresent(String.self, forKey: .correctionRationale) ?? "Standard English requires this correction to match accepted grammatical usage patterns."
    }
    
    // Updated memberwise init for previews and testing
    init(type: String, fullErrantType: String, originalText: String, originalStartChar: Int, originalEndChar: Int, correctedText: String, correctedStartChar: Int, correctedEndChar: Int, correctionRationale: String? = nil) {
        self.type = type
        self.fullErrantType = fullErrantType
        self.originalText = originalText
        self.originalStartChar = originalStartChar
        self.originalEndChar = originalEndChar
        self.correctedText = correctedText
        self.correctedStartChar = correctedStartChar
        self.correctedEndChar = correctedEndChar
        if let rationale = correctionRationale {
            self.correctionRationale = rationale
        }
    }
    
    var description: String {
        return """
        Error Type: \(self.type)
        
        """
    }
}
